name: Check Instructor's Change

on:
  pull_request:
    branches:
      - main

jobs:
  check-change:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Test
      run: |
        $changeExists = git log --pretty=%B -n 1 HEAD | Select-String -Pattern "ðŸ¥›"
        if ($changeExists) {
          Write-Host "Test bestanden: Die Ã„nderung des Instructors wurde gefunden."
          exit 0
        } else {
          Write-Host "Test fehlschlagen: Die Ã„nderung des Instructors wurde nicht gefunden."
          exit 1
        }
      shell: pwsh
